CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION "user";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
GRANT ALL PRIVILEGES ON SCHEMA app TO "user";
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON TABLES TO "user";
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON SEQUENCES TO "user";
